# Generated by Django 6.1.1 on 2026-09-08 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CravingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('craving_text', models.CharField(max_length=255)),
                ('suggested_alternative', models.JSONField(default=dict, help_text='Healthier recipe/alternative details JSON')),
                ('dietary_preference_used', models.CharField(default='vegetarian', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='craving_requests', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='nutrition_c_patient_d48b07_idx')],
            },
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(help_text='Uploaded food meal photo', upload_to='food_logs/%Y/%m/')),
                ('recognized_food_name', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('nutrition_breakdown', models.JSONField(default=dict, help_text='Macronutrient and calorie breakdown JSON')),
                ('logged_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['patient', '-logged_at'], name='nutrition_f_patient_316de5_idx')],
            },
        ),
    ]
