# Generated by Django 6.1.1 on 2026-09-08 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('ai', 'AI Generated'), ('doctor', 'Doctor Authored')], default='ai', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('category', models.CharField(choices=[('hydration', 'Hydration'), ('diet', 'Diet & Nutrition'), ('exercise', 'Exercise & Movement'), ('lifestyle', 'Sleep & Lifestyle'), ('medication', 'Medication & Supplements')], default='lifestyle', max_length=20)),
                ('text', models.TextField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_suggestions', to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='suggestions_patient_ca29ca_idx'), models.Index(fields=['doctor', 'status'], name='suggestions_doctor__41b7d1_idx')],
            },
        ),
    ]
