# Generated by Django 6.1.1 on 2026-09-08 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('signal_source', models.CharField(default='vitals', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence between 0.0 and 1.0')),
                ('is_estimated', models.BooleanField(default=True, help_text='True if derived via vitals, False if logged by user')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alcohol_signals', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['patient', '-timestamp'], name='wearables_a_patient_641378_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExerciseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('activity_type', models.CharField(default='walking', max_length=100)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('intensity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('source_provider', models.CharField(default='health_connect', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_entries', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['patient', '-date'], name='wearables_e_patient_c50d76_idx')],
                'unique_together': {('patient', 'date', 'activity_type')},
            },
        ),
        migrations.CreateModel(
            name='SleepEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('total_sleep_minutes', models.PositiveIntegerField(help_text='Total sleep duration in minutes')),
                ('deep_sleep_minutes', models.PositiveIntegerField(help_text='Deep sleep duration in minutes')),
                ('rem_sleep_minutes', models.PositiveIntegerField(default=0, help_text='REM sleep in minutes')),
                ('light_sleep_minutes', models.PositiveIntegerField(default=0, help_text='Light sleep in minutes')),
                ('source_provider', models.CharField(default='health_connect', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_entries', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['patient', '-date'], name='wearables_s_patient_a8f431_idx')],
                'unique_together': {('patient', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WearableConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('boat_wave', 'boAt Wave'), ('health_connect', 'Google Health Connect'), ('healthkit', 'Apple HealthKit')], max_length=50)),
                ('access_token', models.TextField(help_text='OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-connected_at'],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
