# Generated by Django 6.1.1 on 2026-09-08 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField()),
                ('flow_intensity', models.CharField(choices=[('light', 'Light'), ('normal', 'Normal'), ('heavy', 'Heavy')], default='normal', max_length=10)),
                ('symptoms', models.JSONField(blank=True, default=list, help_text="List of symptoms experienced, e.g. ['cramps', 'bloating', 'fatigue']")),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_entries', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['patient', '-start_date'], name='cycles_cycl_patient_2aea0a_idx')],
            },
        ),
    ]
